model:
  name: bisenet (FDA)

train:
  epochs: 50
  batch_size: 4
  lr: 0.01

data:
  dir_train: /content/semantic_segmentation-25/datasets/data/GTA5
  dir_val: /content/semantic_segmentation-25/datasets/data/Cityscapes/Cityspaces
  img_size_train: [720, 1280]
  img_size_val: [512, 1024]

fda:
  beta: 0.01
  charbonnier_eps: 0.000001
  charbonnier_alpha: 0.5
  lambda_ent: 0.001